version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:80
    environment:
      - DATABASE_URL=postgresql://paymentsystem:paymentsystem@db:5432/paymentsystem
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=paymentsystem
      - POSTGRES_PASSWORD=paymentsystem
      - POSTGRES_DB=paymentsystem

volumes:
  postgres_data: